name: Internet Speed Logger

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 5 AM UTC
  workflow_dispatch:  # Manual run if needed

jobs:
  speed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run internet speed test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python internet_speed_logger.py
